version: "3.8"

services:

  backend:
    container_name: backend
    image: mashohle/frontend
    environment:
      - PORT=3000
    build:
      context: ./backend
    ports:
      - 3000:3000
  
  frontend:
    container_name: frontend
    image: mashohle/frontend
    depends_on:
      - backend
    build: 
      context: ./frontend
    ports:
      - 4200:80